#!/system/bin/sh

#Set default values on boot
echo "temporary none" > /sys/class/scsi_disk/0:0:0:1/cache_type
echo "temporary none" > /sys/class/scsi_disk/0:0:0:2/cache_type

#Setup Mhz Min/Max Cluster 0
echo 400000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1500000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 400000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo 1500000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo 400000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo 1500000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo 400000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
echo 1500000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

#Setup Mhz Min/Max Cluster 1
echo 400000 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq
echo 2100000 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq
echo 400000 > /sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq
echo 2100000 > /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq
echo 400000 > /sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq
echo 2100000 > /sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq
echo 400000 > /sys/devices/system/cpu/cpu7/cpufreq/scaling_min_freq
echo 2100000 > /sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq

# Google Services battery drain fixer by Alcolawl@xda
# http://forum.xda-developers.com/google-nexus-5/general/script-google-play-services-battery-t3059585/post59563859
pm enable com.google.android.gms/.update.SystemUpdateActivity
pm enable com.google.android.gms/.update.SystemUpdateService
pm enable com.google.android.gms/.update.SystemUpdateService$ActiveReceiver
pm enable com.google.android.gms/.update.SystemUpdateService$Receiver
pm enable com.google.android.gms/.update.SystemUpdateService$SecretCodeReceiver
pm enable com.google.android.gsf/.update.SystemUpdateActivity
pm enable com.google.android.gsf/.update.SystemUpdatePanoActivity
pm enable com.google.android.gsf/.update.SystemUpdateService
pm enable com.google.android.gsf/.update.SystemUpdateService$Receiver
pm enable com.google.android.gsf/.update.SystemUpdateService$SecretCodeReceiver

